#!/bin/sh
# These tests need to be run with special (e.g., root) permission.
FLAGS="-t"
RUN='rlimit 300'
rm -f run_tests_2.log
$RUN ../p120100 ${FLAGS} >> run_tests_2.log 2>&1
$RUN ../p120400 ${FLAGS} >> run_tests_2.log 2>&1
$RUN ../p120500 ${FLAGS} >> run_tests_2.log 2>&1
$RUN ../p120501 ${FLAGS} >> run_tests_2.log 2>&1
$RUN ../p140100 ${FLAGS} >> run_tests_2.log 2>&1
$RUN ../p150100 ${FLAGS} >> run_tests_2.log 2>&1
$RUN ../p990040 ${FLAGS} >> run_tests_2.log 2>&1
$RUN ../p990050 ${FLAGS} >> run_tests_2.log 2>&1
