#!/bin/sh
# run all the tests that can reasonably run in a batch
# that need special privileges on Solaris 2.7.
#
# FLAGS determines the degree of verbosity of the output.
# Setting it to "-t" give the tersest form of output.
FLAGS="-t"
RUN=
#
# remove the old log file
#
rm -f run_tests_2.log
#
# run the tests
#
if [ ! -h bin ]
then rm -f ./bin;
     ln -fs .. ./bin;
fi
$RUN ../p120100 ${FLAGS} >> run_tests_2.log 2>&1
ln -fs ../p120101
$RUN ../p120101 ${FLAGS} >> run_tests_2.log 2>&1
$RUN ../p120200 ${FLAGS} >> run_tests_2.log 2>&1
$RUN ../p120500 ${FLAGS} >> run_tests_2.log 2>&1
$RUN ../p140101 ${FLAGS} >> run_tests_2.log 2>&1
